### ISSUE TITLE
modern theme and dark mode not working with stache

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-layout#123]
As evident in the preview build for blackbaud/skyux2-docs#949, stache and dark mode look weird. at first it was thought that stache was broken, but i don't know enough about dark mode to know what it's supposed to look like. or how it's implemented. so i can't really debug this. so at bare minimum, the investigation of the issue should start w/ the skyux team.

**Comment by Blackbaud-AlexKingman** [comment]
Thanks for bringing this up, Colby. Alternate color schemes (like dark mode) are completely experimental at this point. There's nothing you need to do to Stache to make it work today. We will be circling back to this at some point in the future. Closing until that further discussion takes place.
