### ISSUE TITLE
 Text not justified not justified for sky-definition-list and  for sky-text-expand scroll coming in modal 

### ISSUE THREAD

**Issue by kamalsingh** [blackbaud/skyux-layout#152]
Expected behavior : 
1. I am using sky-definition-list  in sky-repeater so text should be justified (right aligned). 
2. I am using sky-text-expand  in sky-repeater, scroll should not come in modal.

Actual behavior : 
1. I am using sky-definition-list  in sky-repeater but text is not justified (right aligned) . (attached image_1.png).
2. I am using sky-text-expand  in sky-repeater but scroll is coming in modal. (attached image_2.
png).

Steps to reproduce - 
Use large text in sky-definition-list in sky-repeater and use large text in sky-text-expand.

Severity - medium

I have attached images for issues.
![image_2](https://user-images.githubusercontent.com/5894278/91718573-435b0a00-ebb1-11ea-8521-91f787cbbbbf.png)
![image_1](https://user-images.githubusercontent.com/5894278/91718578-448c3700-ebb1-11ea-93ed-071c26642ea8.png)

**Comment by Blackbaud-DanMiller** [comment]
left-hand justification in definition list is valid. moved text expand modal wrapping issue to #153
