### ISSUE TITLE
Text Expand Modal does not wrap long unbroken line of text by default

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [blackbaud/skyux-layout#153]
![image.png](https://images.zenhubusercontent.com/5c98c76baa53260001acd226/c57e92af-d1f0-45e4-9356-0da81cfe7ea9)

[AB#1565287](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1565287)

**Comment by Blackbaud-TrevorBurch** [comment]
@kamalsingh originally filed this issue.

PR: #174

**Comment by Blackbaud-TrevorBurch** [comment]
Fixed in `4.3.1`
