### ISSUE TITLE
SkyActionButtonFixture unit tests fail

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-layout#206]
Unit tests that passed in @skyux/layout@4.5.1 fail in @skyux/layout@4.5.2 and I don't see a workaround besides just disabling the tests.

This is a known issue but I do not see an issue filed for it. See note here: https://github.com/blackbaud/skyux-layout/blob/46f8cc1c6a3b3a590862a9e74e44110245489806/src/app/public/testing/action-button-fixture.spec.ts#L52

[AB#1788746](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1788746)

**Comment by Blackbaud-ChristiSchneider** [comment]
I think this is worth mentioning in the CHANGELOG at least, especially considering this was a patch version update.

**Comment by Blackbaud-AlexKingman** [comment]
This seems to have been fixed from previous releases. Closing.
