### ISSUE TITLE
Text Expand Repeater - Support objects as repeater items

### ISSUE THREAD

**Issue by Blackbaud-CoreyArcher** [blackbaud/skyux-layout#40]
My team would like to display a list of elements in a block, and use the text-expand functionality to hide more than a prescribed number of elements. These elements contain multiple properties that we would like to display in a formatted line, for example:
* **Title_1** *1/19/01 - Present*
* **Title_2** *3/17/05 - 8/09/10* __See more__

However, the `sky-text-expand-repeater` component is only capable of properly displaying primitive types like strings and numbers. We would like to contribute the ability to supply child content to the component as a template for the element objects.

**Comment by Blackbaud-SteveBrush** [comment]
This will more than likely need design approval; do you mind reaching out to your UX designer?

**Comment by Blackbaud-ScottZetrouer** [comment]
Just to clarify, we're attempting to port the existing "Lists" from RE NXT from SkyUX1 to latest. The above display of data was design approved years ago, but we obviously weren't using `sky-text-expand-repeater`. This is a common pattern in the old Lists, so we'd likely be using this quite a bit. 

Do we need design approval of the visual choice of how the data is displayed, or is it more about the idea of altering that component or whether it is the correct component to try to leverage?

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-CoreyArcher I'm going to bring this up to our UX designer during standup today. I'll update this thread immediately afterwards.

**Comment by Blackbaud-CoreyArcher** [comment]
Sounds good. FYI if you hadn't seen it, PR #43 has all of the code changes we were planning on making for this change.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-CoreyArcher Sorry for the late reply, but we're going to start the review process early next week (for your PR).
