### ISSUE TITLE
sky-column loses class

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-layout#45]
### Expected behavior

`class` on `sky-column` will be included in compiled html, allowing the style for the column to be changed

### Actual behavior

Specified `class` attributes are not included on `sky-column`

### Steps to reproduce

https://stackblitz.com/edit/angular-2av6le

### Severity

Low, can workaround by specifying `style` tag

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-ChristiSchneider Curious what purpose you're trying to accomplish by adding a classname to the component tag?

**Comment by Blackbaud-ChristiSchneider** [comment]
I wanted to center the text. Adding the `text-align` style to the contents of the `sky-column` does not center the text.

**Comment by Blackbaud-AlexKingman** [comment]
The proposed workaround for this is to include a class on a child element of `sky-column`. Closing.
