### ISSUE TITLE
Selected action button has very strange border 

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux-layout#82]
### Expected behavior
Expect the selected button to have a highlighted border around the button.

### Actual behavior
See bizarre border outline.

![image](https://user-images.githubusercontent.com/11995039/75208096-9b1f4100-5748-11ea-8e95-159d09fe5dd6.png)

### Steps to reproduce
1. Go here https://developer.blackbaud.com/skyux/components/action-button
2. Click button that launches modal, or click and drag off of link button so it doesn't navigate.
3. View ugly border.

### Impact
My eyes

**Comment by Blackbaud-SteveBrush** [comment]
This was fixed: https://github.com/blackbaud/skyux-layout/blob/master/CHANGELOG.md#360-2020-02-03
