### ISSUE TITLE
Enhancement request: For fluid grid, allow single "screen" property that can be overridden by properties like "screenXSmall", "screenLarge", etc.

### ISSUE THREAD

**Issue by Blackbaud-AnthonyDuncan** [blackbaud/skyux-layout#91]
### Expected behavior
Allow single `screen` property to be the default value for `screenXSmall`, `screenSmall`, `screenMedium`, `screenLarge` if those values are not provided. Any value that is provided would override whatever is given in `screen`.

### Actual behavior
The `screen` property doesn't exist, so its currently a no-op.

### Steps to reproduce
Expected / enhanced behavior
```
<sky-column screen="1">
```
vs. actual behavior
```
<sky-column screenXSmall="1" screenSmall="1" screenMedium="1" screenLarge="1">
```

### Severity
Minor

### Impact
Medium / Low

**Comment by Blackbaud-DanMiller** [comment]
This is intended behavior per the documentation: https://developer.blackbaud.com/skyux/components/fluid-grid#column-properties

SKY UX is mobile-first, and it was a deliberate decision to treat screenXSmall as the "base" that other screen sizes inherit from.

Will not address.
